* Improvements to configure/build failure detection, more environment setup for builds.  * Always add "application" to CATEGORY.

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -135,11 +135,18 @@ MAINTAINER?=	ports@solports.org
 # Get the machine arch
 ifndef ARCH
 ARCH=	$(shell uname -p)
+ISAINFO=$(shell isainfo)
+# XXX: Add proper code to check for 64-bitness
+#ifneq (,$(filter amd64 sparcv9,$(ISAINFO)))
+#CFLAGS+=	-m64
+#endif
 endif
 
 ifeq (,$(findstring $(ARCH),$(ARCHES)))
 $(error $(PKGNAME) does not run on the $(ARCH) platform.)
 endif
+
+CC:=	gcc
 
 # Application paths
 AWK?=	/usr/xpg4/bin/awk
@@ -151,11 +158,15 @@ WGET?=	/usr/sfw/bin/wget
 
 ALL_FAKE_FLAGS=	$(DESTDIRNAME)=$(FAKE_PREFIX)
 _FAKE_SETUP=	PREFIX=$(WRKINST) $(DESTDIRNAME)=$(WRKINST)
-MAKE_ENV?=		PREFIX=$(PREFIX)
+MAKE_ENV?=		PREFIX=$(PREFIX) CC=$(CC) CFLAGS=$(CFLAGS) \
+				CXX=$(CXX) CXXFLAGS=$(CXXFLAGS)
 CONFIGURE_SCRIPT?=configure
 DESTDIRNAME?=	DESTDIR
 ALL_TARGET?=	all
 INSTALL_TARGET?=install
+
+CONFIGURE_ENV?=	PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/local/lib/pkgconfig \
+				CC=$(CC) CFLAGS=$(CFLAGS) CXX=$(CXX) CXXFLAGS=$(CXXFLAGS)
 
 ifeq (.tar.gz,$(EXTRACT_SUFX))
 EXTRACT_CMD?=	/usr/bin/gzip
@@ -335,7 +346,11 @@ ifdef HAS_CONFIGURE
 		$(DO_NADA); \
 	else \
 		echo "==> Configuring for $(PKGNAME)"; \
-		cd $(WRKSRC) && ./$(CONFIGURE_SCRIPT) $(CONFIGURE_ARGS); \
+		cd $(WRKSRC) && $(ENV) $(CONFIGURE_ENV) ./$(CONFIGURE_SCRIPT) $(CONFIGURE_ARGS); \
+		if [ $$? -gt 0 ]; then \
+			echo "===> Configure failed."; \
+			exit 1; \
+		fi; \
 		touch $(WRKDIR)/.configure_done; \
 	fi
 endif
@@ -347,6 +362,10 @@ ifndef NO_BUILD
 	else \
 		echo "==> Building for $(PKGNAME)"; \
 		cd $(WRKSRC) && $(MAKE) $(MAKE_ARGS) $(ALL_TARGET); \
+		if [ $$? -gt 0 ]; then \
+			echo "===> Build failed."; \
+			exit 1; \
+		fi; \
 		touch $(WRKDIR)/.build_done; \
 	fi
 endif
@@ -366,12 +385,17 @@ pkg: install $(PKGFILE)
 pkginfo: $(PKGINFO)
 prototype: $(PROTOTYPE)
 
+comma := ,
+empty :=
+space := $(empty) $(empty)
+CATEGORY:=$(subst $(space),$(comma),$(CATEGORY))
+
 $(PKGINFO):
 	@if [ -f $@ ]; then rm $@; fi
 	@echo "PKG=$(PKGNAMEPREFIX)$(NAME)" >> $@
 	@echo "NAME=$(DESC)" >> $@
 	@echo "VERSION=$(VERSION)" >> $@
-	@echo "CATEGORY=$(CATEGORY)" >> $@
+	@echo "CATEGORY=application,$(CATEGORY)" >> $@
 	@echo "ARCH=$(ARCH)" >> $@
 ifdef PKGLONGDESC
 	@echo "DESC=$(LONGDESC)" >> $@
@@ -436,7 +460,7 @@ ifdef SMF_MANIFEST
 	@svccfg validate $(PKGDIR)/smf/$(SMF_MANIFEST); \
 	if [ $$? -gt 0 ]; then \
 		echo "===> Error: SMF manifest did not validate."; \
-		exit $$?; \
+		exit 1; \
 	fi
 	@echo "!search $(PKGDIR)" >> $@
 ifdef SMF_METHOD
